# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-dev
# spec:
#   selector:
#     matchLabels:
#       app: nginx-dev
#   template:
#     metadata:
#       labels:
#         app: nginx-dev
#     spec:
#       containers:
#       - name: nginx-dev
#         image: nginx:latest
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80